openapi: 3.0.0
info:
  title: Music Playlist Service
  description: "This is the API definition for the Music Playlist Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Playlists
    description: Create, view, and update playlists

  - name: Songs
    description: View and add songs to playlists

  - name: Projects
    description: Create, view, and update projects
    
  - name: Tickets
    description: view, add, and update tickets

paths:
  /projects:
    post:
      tags:
        - Projects
      summary: Create a new project (CreateProjectLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        "200":
          description: A project object
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectId:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string

  /projects/{projectid}/tickets:
    post:
      tags:
        - Tickets
      summary: Create a new Tickets (CreateTicketsLambda)
      operationId: createTicket
      parameters:
        - name: projectid
          in: path
          description: project for new ticket
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        "200":
          description: A ticket object
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectId:
                    type: string
                  tickedId:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
        "500":
          description: "Invalid input parameters"

  /playlists:
    post:
      tags:
        - Playlists
      summary: Create a new playlist (CreatePlaylistLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                customerId:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: A playlist object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  songCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string

  /playlists/{id}:
    get:
      tags:
        - Playlists
      summary: Get an existing playlist (GetPlaylistLambda)
      parameters:
        - name: id
          in: path
          description: ID of playlist to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: PlaylistResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  songCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
        "500":
          description: "Invalid input parameters"

    put:
      tags:
        - Playlists
      summary: Update the name of an existing playlist (UpdatePlaylistLambda)
      parameters:
        - name: id
          in: path
          description: ID of playlist to retrieve
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                customerId:
                  type: string

      responses:
        "200":
          description: PlaylistResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  customerId:
                    type: string
                  songCount:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string
        "500":
          description: "Invalid input parameters"

  /playlists/{id}/songs:
    get:
      tags:
        - Songs
      summary: Retrieves a list of all songs in a playlist (GetPlaylistSongsLambda)
      operationId: getSongs
      parameters:
        - name: id
          in: path
          description: ID of playlist to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A playlist object
          content:
            application/json:
              schema:
                type: object
                properties:
                  songList:
                    type: array
                    items:
                      properties:
                        asin:
                          type: string
                        title:
                          type: string
                        album:
                          type: string
                        trackNumber:
                          type: integer

    post:
      tags:
        - Songs
      summary: Add a song to a playlist (AddSongToPlaylistLambda)
      operationId: addSong
      parameters:
        - name: id
          in: path
          description: ID of playlist to return
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                asin:
                  type: string
                trackNumber:
                  type: integer
                id:
                  type: string

      responses:
        "200":
          description: the song
          content:
            application/json:
              schema:
                type: object
                properties:
                  songList:
                    type: array
                    items:
                      properties:
                        asin:
                          type: string
                        title:
                          type: string
                        album:
                          type: string
                        trackNumber:
                          type: integer


  /projects/{projectid}/tickets/{ticketid}:
    get:
      summary: receive a ticket by its ticketId
      operationId: getTicket
      parameters:
        - name: projectid
          in: path
          description: id of the project to retrieve tickets from
          required: true
          schema:
            type: string
        - name: ticketid
          in: path
          description: id of the ticket to receive
          required: true
          schema:
            type: string
      responses:
        "200":
          description: a TaskModel
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectId:
                    type: string
                  ticketId:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
        "404":
          description: Ticket with the specified "ticketId" was not found
